services:
  backend:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  worker:
    command: ["celery", "-A", "config", "worker", "--loglevel=info", "--pool=solo"]
    volumes:
      - ./backend:/app

  beat:
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - ./backend:/app

  frontend:
    command: ["sh", "-c", "npm install && npm run dev"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
