# Generated by Django 5.2.12 on 2026-03-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0001_initial'),
        ('screens', '0001_initial'),
        ('universes', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workflow_kind', models.CharField(choices=[('screen', 'Screen'), ('backtest', 'Backtest')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_templates', to=settings.AUTH_USER_MODEL)),
                ('source_backtest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_templates', to='backtests.backtestrun')),
                ('source_screen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_templates', to='screens.screenrun')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_templates', to='universes.universe')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'workflow_kind', 'updated_at'], name='strategy_te_workspa_ce89c4_idx'), models.Index(fields=['workspace', 'name'], name='strategy_te_workspa_d0872f_idx')],
            },
        ),
    ]
