# Generated by Django 5.2.12 on 2026-03-18 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_backtestrun_is_starred_backtestrun_notes_and_more'),
        ('screens', '0003_screenrun_is_starred_screenrun_notes_screenrun_tags'),
        ('strategy_templates', '0002_strategytemplate_is_starred_strategytemplate_notes_and_more'),
        ('universes', '0002_universe_is_starred_universe_notes_universe_tags'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytemplate',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_strategy_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='strategytemplate',
            index=models.Index(fields=['workspace', 'review_status', 'updated_at'], name='strategy_te_workspa_5f2f02_idx'),
        ),
    ]
