# Generated by Django 5.2.12 on 2026-03-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('universes', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_n', models.PositiveIntegerField(default=30)),
                ('momentum_mode', models.CharField(default='none', max_length=16)),
                ('sector_allowlist', models.JSONField(blank=True, default=list)),
                ('min_market_cap', models.FloatField(blank=True, null=True)),
                ('exclude_financials', models.BooleanField(default=True)),
                ('exclude_utilities', models.BooleanField(default=True)),
                ('exclude_adrs', models.BooleanField(default=True)),
                ('use_cache', models.BooleanField(default=True)),
                ('refresh_cache', models.BooleanField(default=False)),
                ('cache_ttl_hours', models.FloatField(default=24.0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('exclusion_count', models.PositiveIntegerField(default=0)),
                ('resolved_ticker_count', models.PositiveIntegerField(default=0)),
                ('total_candidate_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('export_storage_backend', models.CharField(blank=True, max_length=50)),
                ('export_storage_key', models.CharField(blank=True, max_length=500)),
                ('export_filename', models.CharField(blank=True, max_length=255)),
                ('export_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('export_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screen_runs', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_run', to='jobs.jobrun')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen_runs', to='universes.universe')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScreenResultRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('ebit', models.FloatField(blank=True, null=True)),
                ('net_working_capital', models.FloatField(blank=True, null=True)),
                ('enterprise_value', models.FloatField(blank=True, null=True)),
                ('return_on_capital', models.FloatField(blank=True, null=True)),
                ('earnings_yield', models.FloatField(blank=True, null=True)),
                ('momentum_6m', models.FloatField(blank=True, null=True)),
                ('roc_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('ey_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('momentum_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('composite_score', models.PositiveIntegerField(blank=True, null=True)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('row_payload', models.JSONField(blank=True, default=dict)),
                ('screen_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_rows', to='screens.screenrun')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScreenExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('screen_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='screens.screenrun')),
            ],
            options={
                'ordering': ['ticker', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='screenrun',
            index=models.Index(fields=['workspace', 'created_at'], name='screens_scr_workspa_698c21_idx'),
        ),
        migrations.AddIndex(
            model_name='screenrun',
            index=models.Index(fields=['universe', 'created_at'], name='screens_scr_univers_e10643_idx'),
        ),
        migrations.AddConstraint(
            model_name='screenresultrow',
            constraint=models.UniqueConstraint(fields=('screen_run', 'position'), name='uniq_screen_result_row_position'),
        ),
        migrations.AddConstraint(
            model_name='screenresultrow',
            constraint=models.UniqueConstraint(fields=('screen_run', 'ticker'), name='uniq_screen_result_row_ticker'),
        ),
        migrations.AddIndex(
            model_name='screenexclusion',
            index=models.Index(fields=['screen_run', 'ticker'], name='screens_scr_screen__15f45d_idx'),
        ),
    ]
