# Generated by Django 5.2.12 on 2026-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_screenrun_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenrun',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screenrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='screenrun',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
