# Generated by Django 5.2.12 on 2026-03-18 13:45

import apps.collaboration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_collections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-is_pinned', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(choices=[('strategy_template', 'Strategy template'), ('run_schedule', 'Run schedule'), ('screen_run', 'Screen run'), ('backtest_run', 'Backtest run')], max_length=32)),
                ('resource_id', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collaboration.workspacecollection')),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(choices=[('strategy_template', 'Strategy template'), ('run_schedule', 'Run schedule'), ('screen_run', 'Screen run'), ('backtest_run', 'Backtest run')], max_length=32)),
                ('resource_id', models.PositiveIntegerField()),
                ('verb', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='collaborati_workspa_f1125d_idx'), models.Index(fields=['workspace', 'resource_kind', 'resource_id', 'created_at'], name='collaborati_workspa_b729c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(choices=[('strategy_template', 'Strategy template'), ('run_schedule', 'Run schedule'), ('screen_run', 'Screen run'), ('backtest_run', 'Backtest run')], max_length=32)),
                ('resource_id', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_comments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_comments', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['workspace', 'resource_kind', 'resource_id', 'created_at'], name='collaborati_workspa_6d06fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(choices=[('strategy_template', 'Strategy template'), ('run_schedule', 'Run schedule'), ('screen_run', 'Screen run'), ('backtest_run', 'Backtest run')], max_length=32)),
                ('resource_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(default=apps.collaboration.models.generate_share_token, max_length=255, unique=True)),
                ('access_scope', models.CharField(choices=[('workspace_member', 'Workspace member'), ('token', 'Anyone with the link')], default='token', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_share_links', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_share_links', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'resource_kind', 'resource_id', 'created_at'], name='collaborati_workspa_0c53a1_idx'), models.Index(fields=['workspace', 'revoked_at', 'created_at'], name='collaborati_workspa_389a0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspacecollection',
            index=models.Index(fields=['workspace', 'is_pinned', 'updated_at'], name='collaborati_workspa_8d000e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecollectionitem',
            index=models.Index(fields=['collection', 'position'], name='collaborati_collect_5468d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacecollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'resource_kind', 'resource_id'), name='uniq_collection_item_resource'),
        ),
    ]
