# Generated by Django 5.2.12 on 2026-03-18 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtests', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('jobs', '0001_initial'),
        ('screens', '0001_initial'),
        ('strategy_templates', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('screen_completed', 'Screen completed'), ('backtest_completed', 'Backtest completed'), ('run_failed', 'Run failed'), ('ticker_entered_top_n', 'Ticker entered top N')], max_length=64)),
                ('workflow_kind', models.CharField(blank=True, choices=[('', 'Any'), ('screen', 'Screen'), ('backtest', 'Backtest')], default='', max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=32)),
                ('destination_email', models.EmailField(blank=True, max_length=254)),
                ('ticker', models.CharField(blank=True, max_length=32)),
                ('top_n_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('strategy_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='strategy_templates.strategytemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RunSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('cron_minute', models.CharField(default='0', max_length=64)),
                ('cron_hour', models.CharField(default='13', max_length=64)),
                ('cron_day_of_week', models.CharField(default='1-5', max_length=64)),
                ('cron_day_of_month', models.CharField(default='*', max_length=64)),
                ('cron_month_of_year', models.CharField(default='*', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('notify_on_success', models.BooleanField(default=True)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_launch_status', models.CharField(blank=True, max_length=32)),
                ('last_run_workflow_kind', models.CharField(blank=True, max_length=32)),
                ('last_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_job_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_schedules', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenblatt_run_schedule', to='django_celery_beat.periodictask')),
                ('strategy_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_schedules', to='strategy_templates.strategytemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_schedules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('delivery_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='automation.alertrule')),
                ('backtest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='backtests.backtestrun')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='jobs.jobrun')),
                ('screen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='screens.screenrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='workspaces.workspace')),
                ('run_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='automation.runschedule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['workspace', 'event_type', 'is_enabled'], name='automation__workspa_0396d8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['workspace', 'workflow_kind', 'updated_at'], name='automation__workspa_66953e_idx'),
        ),
        migrations.AddIndex(
            model_name='runschedule',
            index=models.Index(fields=['workspace', 'is_enabled', 'updated_at'], name='automation__workspa_6d2007_idx'),
        ),
        migrations.AddIndex(
            model_name='runschedule',
            index=models.Index(fields=['workspace', 'strategy_template', 'updated_at'], name='automation__workspa_afdee1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='automation__workspa_edc355_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['workspace', 'event_type', 'created_at'], name='automation__workspa_baa732_idx'),
        ),
    ]
