# Generated by Django 5.2.12 on 2026-03-18 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('strategy_templates', '0002_strategytemplate_is_starred_strategytemplate_notes_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_email', models.EmailField(blank=True, max_length=254)),
                ('email_enabled', models.BooleanField(default=True)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['workspace_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email', models.EmailField(blank=True, max_length=254)),
                ('email_enabled', models.BooleanField(default=True)),
                ('slack_enabled', models.BooleanField(default=True)),
                ('webhook_enabled', models.BooleanField(default=True)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('generic_webhook_url', models.URLField(blank=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_hour_utc', models.PositiveSmallIntegerField(default=9)),
                ('notify_on_run_success', models.BooleanField(default=True)),
                ('notify_on_run_failure', models.BooleanField(default=True)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['workspace_id'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='destination_webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='recipient_webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'Email'), ('slack_webhook', 'Slack webhook'), ('webhook', 'Generic webhook')], default='email', max_length=32),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='notify_webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runschedule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_run_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('slack_webhook', 'Slack webhook'), ('webhook', 'Generic webhook')], default='email', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('slack_webhook', 'Slack webhook'), ('webhook', 'Generic webhook'), ('digest', 'Digest')], default='email', max_length=32),
        ),
        migrations.AddIndex(
            model_name='runschedule',
            index=models.Index(fields=['workspace', 'review_status', 'updated_at'], name='automation__workspa_347b58_idx'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspacenotificationpreference',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationpreference',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_user_notification_preference_workspace_user'),
        ),
    ]
