# Generated by Django 5.2.12 on 2026-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_usernotificationpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='slack_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='webhook_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
