# Generated by Django 5.2.12 on 2026-03-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('universes', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.FloatField(default=100000.0)),
                ('portfolio_size', models.PositiveIntegerField(default=20)),
                ('review_frequency', models.CharField(default='W-FRI', max_length=32)),
                ('benchmark', models.CharField(blank=True, default='^GSPC', max_length=32)),
                ('momentum_mode', models.CharField(default='none', max_length=16)),
                ('sector_allowlist', models.JSONField(blank=True, default=list)),
                ('min_market_cap', models.FloatField(blank=True, null=True)),
                ('use_cache', models.BooleanField(default=True)),
                ('refresh_cache', models.BooleanField(default=False)),
                ('cache_ttl_hours', models.FloatField(default=24.0)),
                ('equity_point_count', models.PositiveIntegerField(default=0)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('review_target_count', models.PositiveIntegerField(default=0)),
                ('final_holding_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('export_storage_backend', models.CharField(blank=True, max_length=50)),
                ('export_storage_key', models.CharField(blank=True, max_length=500)),
                ('export_filename', models.CharField(blank=True, max_length=255)),
                ('export_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('export_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backtest_runs', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_run', to='jobs.jobrun')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backtest_runs', to='universes.universe')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BacktestReviewTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('target_rank', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('composite_score', models.PositiveIntegerField(blank=True, null=True)),
                ('roc_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('ey_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('momentum_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_targets', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BacktestFinalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=32)),
                ('shares', models.FloatField()),
                ('entry_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_holdings', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BacktestEquityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('cash', models.FloatField()),
                ('equity', models.FloatField()),
                ('positions', models.PositiveIntegerField()),
                ('benchmark_equity', models.FloatField(blank=True, null=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_points', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=8)),
                ('shares', models.FloatField()),
                ('price', models.FloatField()),
                ('proceeds', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtestrun')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['workspace', 'created_at'], name='backtests_b_workspa_84c1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['universe', 'created_at'], name='backtests_b_univers_aeb517_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestreviewtarget',
            index=models.Index(fields=['backtest_run', 'date'], name='backtests_b_backtes_94b806_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestreviewtarget',
            index=models.Index(fields=['backtest_run', 'ticker'], name='backtests_b_backtes_beef94_idx'),
        ),
        migrations.AddConstraint(
            model_name='backtestreviewtarget',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'position'), name='uniq_backtest_review_position'),
        ),
        migrations.AddConstraint(
            model_name='backtestfinalholding',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'position'), name='uniq_backtest_holding_position'),
        ),
        migrations.AddConstraint(
            model_name='backtestfinalholding',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'ticker'), name='uniq_backtest_holding_ticker'),
        ),
        migrations.AddConstraint(
            model_name='backtestequitypoint',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'position'), name='uniq_backtest_equity_position'),
        ),
        migrations.AddConstraint(
            model_name='backtestequitypoint',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'date'), name='uniq_backtest_equity_date'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest_run', 'date'], name='backtests_b_backtes_05f022_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest_run', 'ticker'], name='backtests_b_backtes_f86db2_idx'),
        ),
        migrations.AddConstraint(
            model_name='backtesttrade',
            constraint=models.UniqueConstraint(fields=('backtest_run', 'position'), name='uniq_backtest_trade_position'),
        ),
    ]
